// packages/a2ui-angular/src/lib/adapter/surface.component.ts
import { Component, computed, inject, input } from '@angular/core';
import { basicCatalog, type Catalog, type SurfaceModel } from '@anycms/a2ui-core';
import { A2uiNodeComponent } from './a2ui-node.component';
import { A2UI_SURFACE, type SurfaceContextValue } from './tokens';
import { basicAngularComponents } from '../registry';
import type { AngularComponentRegistry } from './types';

/**
 * Framework entry point (renderer_guide.md §Surface). Renders the `root`
 * component of a surface and provides the surface/catalog/registry to the tree.
 * Structural changes (component add/remove/type-change) are handled reactively
 * inside each `A2uiNode`; the surface does not force-rerender the tree.
 *
 * The provided value is a `computed` signal, so swapping `registry`/`catalog`
 * (e.g. a renderer toggle) re-provides and descendants re-evaluate.
 */
@Component({
  selector: 'a2ui-surface',
  template: `
    <div class="a2ui-surface">
      <a2ui-node [id]="rootId" [basePath]="''" />
    </div>
  `,
  imports: [A2uiNodeComponent],
  providers: [
    // Provide the live surface context as a signal so children stay reactive
    // when inputs change. `useFactory` + `inject` reads the host component.
    { provide: A2UI_SURFACE, useFactory: (): unknown => inject(A2uiSurfaceComponent).surfaceCtx },
  ],
})
export class A2uiSurfaceComponent {
  readonly surface = input.required<SurfaceModel>();
  readonly catalog = input<Catalog>();
  readonly registry = input<AngularComponentRegistry>();

  readonly rootId = 'root';

  readonly surfaceCtx = computed<SurfaceContextValue>(() => ({
    surface: this.surface(),
    catalog: this.catalog() ?? basicCatalog,
    registry: this.registry() ?? basicAngularComponents,
  }));
}

// packages/a2ui-react/src/Surface.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { basicCatalog, type Catalog, type SurfaceModel } from '@anycms/a2ui-core';
import { A2uiNode, SurfaceContext, type ReactComponentRegistry } from './adapter';
import { basicReactComponents } from './registry';

export interface A2uiSurfaceProps {
  surface: SurfaceModel;
  catalog?: Catalog;
  registry?: ReactComponentRegistry;
}

/**
 * Framework entry point (renderer_guide.md §Surface). Renders the `root`
 * component of a surface, and re-renders the tree when components are added or
 * removed. Property/data changes are handled reactively inside each bound node.
 */
export function A2uiSurface({
  surface,
  catalog = basicCatalog,
  registry = basicReactComponents,
}: A2uiSurfaceProps): ReactNode {
  const [, force] = useState(0);

  useEffect(() => {
    const c1 = surface.componentsModel.onCreated.subscribe(() => force((v) => v + 1));
    const c2 = surface.componentsModel.onDeleted.subscribe(() => force((v) => v + 1));
    return () => {
      c1.unsubscribe();
      c2.unsubscribe();
    };
  }, [surface]);

  return (
    <SurfaceContext.Provider value={{ surface, catalog, registry }}>
      <div className="a2ui-surface">
        <A2uiNode id="root" basePath="" />
      </div>
    </SurfaceContext.Provider>
  );
}
